#!/bin/sh

MONIT_AUTH_USERNAME=${MONIT_AUTH_USERNAME:-admin}
MONIT_AUTH_PASSWORD=${MONIT_AUTH_PASSWORD:-changeit}

echo "# Generated by start.sh" > /etc/monit/conf.d/1_httpd.cfg

cat << EOF >> /etc/monit/conf.d/1_httpd.cfg
# Generated by start.sh
set httpd
    port 8080
    use address 0.0.0.0
    allow ${MONIT_AUTH_USERNAME}:${MONIT_AUTH_PASSWORD}
EOF
