#!/bin/sh
echo "# Generated by start.sh" > /etc/monit/conf.d/disk-usage.cfg

cat << EOF >> /etc/monit/conf.d/disk-usage.cfg
# Generated by start.sh
check device sync_dir with path /
    if space usage > 50% then alert
EOF
