#!/bin/sh

ALERTED_EMAIL=${MONIT_ALERTED_EMAIL:-fourcade.m@gmail.com}

echo "# Generated by start.sh" > /etc/monit/conf.d/mail-format.cfg

cat << EOF >> /etc/monit/conf.d/mail-format.cfg
# Generated by start.sh
set mail-format {
  from:    Monit <${ALERTED_EMAIL}>
  subject: monit alert --  $EVENT $SERVICE
  message: $EVENT Service $SERVICE
                Date:        $DATE
                Action:      $ACTION
                Host:        $HOST
                Description: $DESCRIPTION

           Your faithful employee,
           Monit
}
EOF
